# Generated by Django 5.1 on 2024-10-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_carreras_estudiantes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='nonlocalombre',
            new_name='nombre',
        ),
    ]
