# Generated by Django 5.1 on 2024-10-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_nonlocalombre_estudiantes_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='carnet',
            field=models.CharField(max_length=12),
        ),
    ]
